//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_screens_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_screens_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_base_sprites_rrb_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_fcm_base_sprites_rrb_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_rrb_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_rrb_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_base_sprites_rrb_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_fcm_base_sprites_rrb_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_base_sprites_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_fcm_base_sprites_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_base_sprites_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_base_sprites_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_base_sprites_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_fcm_base_sprites_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_screens_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_screens_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_sprites_rrb_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_fcm_sprites_rrb_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_rrb_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_rrb_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_sprites_rrb_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_fcm_sprites_rrb_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_screen {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_sprites_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_fcm_sprites_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_fcm_sprites_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_fcm_sprites_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string export_fcm_sprites_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_fcm_sprites_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_screens_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_screens_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_base_sprites_rrb_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_ncm_base_sprites_rrb_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_rrb_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_rrb_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_base_sprites_rrb_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_ncm_base_sprites_rrb_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_base_sprites_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_ncm_base_sprites_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_base_sprites_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_base_sprites_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_base_sprites_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_ncm_base_sprites_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_screens_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_screens_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_chars {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_colour {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_colour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_lookup {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_lookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_palette {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_palette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_sprites_rrb_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_ncm_sprites_rrb_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_rrb_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_rrb_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_sprites_rrb_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_ncm_sprites_rrb_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_screen {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_screen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_spr_input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_spr_input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_sprites_spr_input_sprite11 {
            get {
                return ResourceManager.GetString("export_ncm_sprites_spr_input_sprite11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] export_ncm_sprites_spr_input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("export_ncm_sprites_spr_input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string export_ncm_sprites_spr_input_sprite21 {
            get {
                return ResourceManager.GetString("export_ncm_sprites_spr_input_sprite21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] input_base_chars {
            get {
                object obj = ResourceManager.GetObject("input_base_chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] input_level {
            get {
                object obj = ResourceManager.GetObject("input_level", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] input_sprite1 {
            get {
                object obj = ResourceManager.GetObject("input_sprite1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] input_sprite2 {
            get {
                object obj = ResourceManager.GetObject("input_sprite2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
